I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 106, in script call
    call Chapter1
  File "game/script.rpy", line 106, in script call
    call Chapter1
ScriptError: could not find label 'Chapter1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 106, in script call
    call Chapter1
  File "renpy/ast.py", line 1490, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 106, in script call
    call Chapter1
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'Chapter1'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
The Hollows 1.0
Wed Feb  9 16:52:03 2022
